const {
  getAllVowels,
  getAllConsonants,
  getShuffledVowels,
  getShuffledConsonants,
  getLetterPoints
} = require('./letters')

test(`Expect vowels to be an array containing: [
    'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a',
    'a', 'a', 'a', 'a', 'a', 'a', 'e', 'e', 'e',
    'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e',
    'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e',
    'i', 'i', 'i', 'i', 'i', 'i', 'i', 'i', 'i',
    'i', 'i', 'i', 'i', 'o', 'o', 'o', 'o', 'o',
    'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'u',
    'u', 'u', 'u', 'u'
  ]`, () => {
  expect(getAllVowels()).toEqual([
    'a',
    'a',
    'a',
    'a',
    'a',
    'a',
    'a',
    'a',
    'a',
    'a',
    'a',
    'a',
    'a',
    'a',
    'a',
    'e',
    'e',
    'e',
    'e',
    'e',
    'e',
    'e',
    'e',
    'e',
    'e',
    'e',
    'e',
    'e',
    'e',
    'e',
    'e',
    'e',
    'e',
    'e',
    'e',
    'e',
    'i',
    'i',
    'i',
    'i',
    'i',
    'i',
    'i',
    'i',
    'i',
    'i',
    'i',
    'i',
    'i',
    'o',
    'o',
    'o',
    'o',
    'o',
    'o',
    'o',
    'o',
    'o',
    'o',
    'o',
    'o',
    'o',
    'u',
    'u',
    'u',
    'u',
    'u'
  ])
})

test(`Expect consonants to be an array containing: [
    'b', 'b', 'c', 'c', 'c', 'd', 'd', 'd', 'd', 'd',
    'd', 'f', 'f', 'g', 'g', 'g', 'h', 'h', 'j', 'k',
    'l', 'l', 'l', 'l', 'l', 'm', 'm', 'm', 'm', 'n',
    'n', 'n', 'n', 'n', 'n', 'n', 'n', 'p', 'p', 'p',
    'p', 'q', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r',
    'r', 's', 's', 's', 's', 's', 's', 's', 's', 's',
    't', 't', 't', 't', 't', 't', 't', 't', 't', 'v',
    'w', 'x', 'x', 'y', 'z'
  ]`, () => {
  expect(getAllConsonants()).toEqual([
    'b',
    'b',
    'c',
    'c',
    'c',
    'd',
    'd',
    'd',
    'd',
    'd',
    'd',
    'f',
    'f',
    'g',
    'g',
    'g',
    'h',
    'h',
    'j',
    'k',
    'l',
    'l',
    'l',
    'l',
    'l',
    'm',
    'm',
    'm',
    'm',
    'n',
    'n',
    'n',
    'n',
    'n',
    'n',
    'n',
    'n',
    'p',
    'p',
    'p',
    'p',
    'q',
    'r',
    'r',
    'r',
    'r',
    'r',
    'r',
    'r',
    'r',
    'r',
    's',
    's',
    's',
    's',
    's',
    's',
    's',
    's',
    's',
    't',
    't',
    't',
    't',
    't',
    't',
    't',
    't',
    't',
    'v',
    'w',
    'x',
    'x',
    'y',
    'z'
  ])
})

test('Shuffle vowels array and return', () => {
  expect(getAllVowels()).not.toEqual(getShuffledVowels())
})

test('Shuffle consonants array and return', () => {
  expect(getAllConsonants()).not.toEqual(getShuffledConsonants())
})

test('Check correct points given for a provided letter',()=>{
  expect(getLetterPoints('z')).toBe(5)
  expect(getLetterPoints('u')).toBe(3)
  expect(getLetterPoints('s')).toBe(1)
})